name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Build
        run: dotnet build --configuration Release

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: MogHouseCompanion
          path: MogHouseCompanion/bin/x64/Release/MogHouseCompanion/*
          if-no-files-found: error
          retention-days: 7
